### ISSUE TITLE
Uncaught Error: Command failed:  /Users/Nadeem/Code/Meteor/Sembly/server/config.js -o /var/folder...

### ISSUE THREAD

**Issue by nadeemja** [jaunkst/atom-lebab-convert#1]
[Enter steps to reproduce below:]

1. Try to use atom-lebab-convert

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [lebab-convert](https://github.com/jaunkst/atom-lebab-convert) package, v0.9.0

### Stack Trace

Uncaught Error: Command failed:  /Users/Nadeem/Code/Meteor/Sembly/server/config.js -o /var/folders/66/4twr7b_5773gsqx67dxmkm000000gn/T/config.js.1462716210322
/bin/sh: /Users/Nadeem/Code/Meteor/Sembly/server/config.js: Permission denied

```
At child_process.js:519

Error: Command failed:  /Users/Nadeem/Code/Meteor/Sembly/server/config.js -o /var/folders/66/4twr7b_5773gsqx67dxmkm000000gn/T/config.js.1462716210322
/bin/sh: /Users/Nadeem/Code/Meteor/Sembly/server/config.js: Permission denied

    at checkExecSyncError (child_process.js:476:13)
    at Object.execSync (child_process.js:516:13)
    at Object._convert (/Users/Nadeem/.atom/packages/lebab-convert/lib/lebab-convert.js:83:19)
    at Object.convert (/Users/Nadeem/.atom/packages/lebab-convert/lib/lebab-convert.js:116:14)
    at atom-workspace.lebabConvertRun (/Users/Nadeem/.atom/packages/lebab-convert/lib/lebab-convert.js:28:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:35.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:35.4.0 lebab-convert:run (atom-text-editor.editor)
     -0:30.7.0 core:move-up (atom-text-editor.editor.is-focused)
  6x -0:30.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:29 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:29 editor:newline (atom-text-editor.editor.is-focused)
     -0:28.8.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:28.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:28.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:23.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:17.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:13.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.1.0 lebab-convert:run (atom-text-editor.editor)
     -0:03.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 lebab-convert:run (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "atom-lupa",
      "tool-bar",
      "sync-settings",
      "atom-ternjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Quick-JavaScript, v0.16.0
atom-bracket-highlight, v0.3.1
atom-ternjs, v0.14.1
autocomplete-modules, v1.4.1
docblockr, v0.7.3
emmet, v2.4.3
formatter, v2.12.3
formatter-jsbeautify, v1.0.2
highlight-column, v0.5.1
highlight-line, v0.11.1
language-babel, v2.20.3
lebab-convert, v0.9.0
linter, v1.11.4
linter-codeclimate, v0.1.2
linter-eslint, v7.2.2
linter-jscs, v4.0.0
meteor-api, v2.20.0
sync-settings, v0.7.2
tool-bar, v0.4.0
tool-bar-almighty, v0.6.1
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by jaunkst** [comment]
Thanks, I am looking into this now.

**Comment by jaunkst** [comment]
Okay, I have tested this on my Mac, and Linux machine. What are the permissions on the file when you 'ls -l config.js' ?

**Comment by nadeemja** [comment]
Hi! 

I got this working by specifying path to lebab (from which lebab) in atom settings :)

**Comment by jaunkst** [comment]
That's great if you have any questions or think I could improve something please let me know.
