### ISSUE TITLE
How do I set the path for atom-lebab-convert? I get an error when running it in Atom

### ISSUE THREAD

**Issue by interglobalmedia** [jaunkst/atom-lebab-convert#2]
Hi,

I just installed atom-lebab-convert, and I come up with an error (this happened when I ran the package in Atom):

Uncaught Error: Command failed: /Users/mariacam/development/fcc-calculator/workflows/gulpDir/tasks/default.js -o /var/folders/q5/tgk035cr8xlgw5001s751fwr0000gn/T/default.js.1469366659385 /bin/sh: /Users/mariacam/development/fcc-calculator/workflows/gulpDir/tasks/default.js: Permission denied
child_process.js:519
Hide Stack Trace
Error: Command failed:  /Users/mariacam/development/fcc-calculator/workflows/gulpDir/tasks/default.js -o /var/folders/q5/tgk035cr8xlgw5001s751fwr0000gn/T/default.js.1469366659385
/bin/sh: /Users/mariacam/development/fcc-calculator/workflows/gulpDir/tasks/default.js: Permission denied
    at checkExecSyncError (child_process.js:476:13)
    at Object.execSync (child_process.js:516:13)
    at Object._convert (/Users/mariacam/.atom/packages/lebab-convert/lib/lebab-convert.js:83:19)
    at Object.convert (/Users/mariacam/.atom/packages/lebab-convert/lib/lebab-convert.js:116:14)
    at atom-workspace.lebabConvertRun (/Users/mariacam/.atom/packages/lebab-convert/lib/lebab-convert.js:28:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/mariacam/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Users/mariacam/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/mariacam/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Users/mariacam/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Users/mariacam/Downloads/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
The error was thrown from the lebab-convert package. You can help by creating an issue. Please explain what actions triggered this error.

**Comment by jaunkst** [comment]
I am going to add a default lebab package as a fallback dependency, and allow the developer to use another version by including it as a dev dependency, and or falling back to a global install.

**Comment by jaunkst** [comment]
https://github.com/jaunkst/atom-lebab-convert/issues/5
