### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by jhlav** [jaunkst/atom-lebab-convert#4]
Steps to reproduce:

1. Write an async function, for example:
```javascript
async function test() {
  await test2();
}
```
2. Run `lebab-convert` package from the Packages menu - error thrown immediately.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [lebab-convert](https://github.com/jaunkst/atom-lebab-convert) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /home/*redacted*/.atom/packages/lebab-convert/lib/lebab-convert.js:108

TypeError: Cannot read property 'path' of null
    at Object.convert (/packages/lebab-convert/lib/lebab-convert.js:108:26)
    at /packages/lebab-convert/lib/lebab-convert.js:28:39)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:33.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-firewatch-syntax.theme-nord-atom-ui)
     -0:25.4.0 lebab-convert:run (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.0.15 
firewatch-syntax 1.1.1 
git-plus 7.3.1 
git-time-machine 1.5.6 
language-babel 2.55.1 
language-cfml 0.16.0 
language-postcss 1.3.0 
lebab-convert 0.9.0 
linter 1.11.23 
linter-eslint 8.1.2 
linter-htmlhint 1.3.1 
linter-stylelint 3.9.0 
minimap 4.26.8 
minimap-find-and-replace 4.5.1 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.6 
nord-atom-ui 0.10.1 
pigments 0.39.0 
react 0.16.2 
remote-sync 4.1.5 
rest-client 1.3.1 
split-diff 1.2.0 
todo-show 1.11.0 
```

**Comment by jaunkst** [comment]
we need to include a default fallback version of lebab in the build. this looks to be failing to find lebab

**Comment by jaunkst** [comment]
https://github.com/jaunkst/atom-lebab-convert/issues/5
